[package]
name = "redstone"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.14.0"
prost = "0.14.0"
tokio = { version = "1", features = ["full"] }
bytes = "1.11.1"
tonic-prost = "0.14.0"

[build-dependencies]
tonic-prost-build = "0.14"

